version: '3'
services:
  app:
    build: .
    ports:
      - 5000:8080
    secrets:
      - test

    # enable if need to get print result
    # environment:
      # - PYTHONUNBUFFERED=1

secrets:
  test:
    file: ./secrets.json